global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: prometheus 
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090    
- job_name: aula  
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics  
  static_configs:
  - targets:    
    - 172.17.0.1:3010  
    ## IP Docker